-- ===========================================================================
-- supabase/lantern_hub_all.sql — everything a NEW Lantern hub needs, in one paste.
-- Generated by scripts/build-hub-sql.mjs from supabase/migrations (0001_lantern_hub.sql, 0002_friends.sql, 0003_lock_helpers.sql).
-- Do not edit this file; edit the migrations and run the script again.
-- Safe to run again. The last result is your one-time owner claim code.
-- ===========================================================================

-- ##########################################################################
-- 0001_lantern_hub.sql
-- ##########################################################################

-- ===========================================================================
-- supabase/migrations/0001_lantern_hub.sql — the Lantern hub.
-- ---------------------------------------------------------------------------
-- Run once in a new (free) Supabase project: SQL Editor → New query → paste
-- this whole file → Run. See docs/setup-supabase.md.
--
-- Shape of the design:
--   * Every table has Row Level Security ON.
--   * Learners never write tables directly. Everything the app does goes
--     through the lantern_* functions below (SECURITY DEFINER), and each one
--     checks who is asking. That keeps the rules in one place.
--   * Reads: a person sees their own rows; the OWNER (profiles.role='owner')
--     sees everything.
--   * Course files live in the private Storage bucket "course-packs". A person
--     can download a course only if they own the hub, were granted it, or it
--     is published and open to everyone.
--   * Nobody is the owner until they claim it with the one-time claim code
--     this script generates (see the end of the file). No email or name is
--     written into this file.
--
-- Everything here is idempotent where Postgres allows, so re-running the file
-- on a project that already has it is safe.
-- ===========================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- people ---

create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text,
  display_name text not null default '',
  role         text not null default 'student' check (role in ('owner', 'student')),
  created_at   timestamptz not null default now()
);

create or replace function public.lantern_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email,
          coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists lantern_on_auth_user on auth.users;
create trigger lantern_on_auth_user after insert on auth.users
  for each row execute function public.lantern_new_user();

-- Values only the functions below may read. No policies = no direct access.
create table if not exists public.app_secrets (
  key   text primary key,
  value text not null
);
insert into public.app_secrets (key, value)
values ('owner_claim_code', encode(gen_random_bytes(9), 'hex'))
on conflict (key) do nothing;

-- --------------------------------------------------------------- courses ---

create table if not exists public.courses (
  id             text primary key check (id ~ '^[a-z0-9][a-z0-9-]{0,39}$'),
  title          text not null,
  description    text not null default '',
  status         text not null default 'draft' check (status in ('draft', 'published')),
  visibility     text not null default 'private' check (visibility in ('private', 'open')),
  listed         boolean not null default false,   -- learners may see the title and ask for it
  latest_version text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.course_versions (
  course_id    text not null references public.courses(id) on delete cascade,
  version      text not null,
  pack_path    text not null,                       -- object name in the course-packs bucket
  size         bigint,
  sha256       text,
  changelog    text not null default '',
  manifest     jsonb,
  published_at timestamptz not null default now(),
  primary key (course_id, version)
);

create table if not exists public.grants (
  user_id    uuid not null references public.profiles(id) on delete cascade,
  course_id  text not null references public.courses(id) on delete cascade,
  granted_by uuid references public.profiles(id) on delete set null,
  via        text not null default 'grant',          -- 'offer' | 'grant' | 'request' | 'group'
  created_at timestamptz not null default now(),
  primary key (user_id, course_id)
);

-- "<owner> sent you ColdFusion": an offer, which the learner accepts or declines.
-- It can be addressed to an account, or to an EMAIL for somebody who has no
-- account yet; it attaches to their account when they sign in with that
-- (verified) email.
create table if not exists public.course_offers (
  id           uuid primary key default gen_random_uuid(),
  from_user    uuid references public.profiles(id) on delete set null,
  to_user      uuid references public.profiles(id) on delete cascade,
  to_email     text,
  course_id    text not null references public.courses(id) on delete cascade,
  message      text not null default '' check (length(message) <= 500),
  status       text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'withdrawn')),
  via          text not null default 'direct',        -- 'direct' | 'invite' | 'group'
  created_at   timestamptz not null default now(),
  responded_at timestamptz,
  check (to_user is not null or to_email is not null)
);
create unique index if not exists course_offers_one_pending
  on public.course_offers (to_user, course_id) where status = 'pending' and to_user is not null;
create unique index if not exists course_offers_one_pending_email
  on public.course_offers (lower(to_email), course_id) where status = 'pending' and to_user is null;

-- A link for somebody who has not signed up yet. Redeeming it creates offers.
create table if not exists public.invites (
  code       text primary key,
  created_by uuid references public.profiles(id) on delete cascade,
  course_ids text[] not null,
  message    text not null default '',
  expires_at timestamptz,
  max_uses   integer,
  uses       integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id  uuid not null references public.profiles(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (group_id, user_id)
);
create table if not exists public.group_courses (
  group_id  uuid not null references public.groups(id) on delete cascade,
  course_id text not null references public.courses(id) on delete cascade,
  message   text not null default '',
  primary key (group_id, course_id)
);

create table if not exists public.course_requests (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  course_id   text not null references public.courses(id) on delete cascade,
  message     text not null default '' check (length(message) <= 500),
  status      text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  created_at  timestamptz not null default now(),
  answered_at timestamptz
);
create unique index if not exists course_requests_one_pending
  on public.course_requests (user_id, course_id) where status = 'pending';

-- ------------------------------------------------------ presence, progress ---

create table if not exists public.presence (
  user_id     uuid not null references public.profiles(id) on delete cascade,
  device_id   text not null,
  last_seen   timestamptz not null default now(),
  app_version text,
  course_id   text,
  lesson_id   text,
  status      text,
  primary key (user_id, device_id)
);

-- Merged by the rules in server/src/platform/merge.js: done stays done, best
-- score wins, times are summed by event id, newest position wins.
create table if not exists public.progress_items (
  user_id       uuid not null references public.profiles(id) on delete cascade,
  course_id     text not null,
  kind          text not null,
  ref           text not null,
  completed     boolean not null default false,
  best          numeric not null default 0,
  attempts      integer not null default 0,
  first_done_at bigint,
  updated_at    bigint not null default 0,
  primary key (user_id, course_id, kind, ref)
);
create table if not exists public.progress_time (
  user_id   uuid not null references public.profiles(id) on delete cascade,
  id        text not null,
  course_id text not null,
  seconds   integer not null check (seconds >= 0),
  at        bigint,
  primary key (user_id, id)
);
create table if not exists public.progress_position (
  user_id   uuid not null references public.profiles(id) on delete cascade,
  course_id text not null,
  ref       text,
  at        bigint not null,
  primary key (user_id, course_id)
);
create table if not exists public.progress_snapshots (
  user_id   uuid not null references public.profiles(id) on delete cascade,
  course_id text not null,
  state     jsonb not null,
  at        bigint not null,
  device_id text,
  primary key (user_id, course_id)
);
create table if not exists public.progress_summary (
  user_id       uuid not null references public.profiles(id) on delete cascade,
  course_id     text not null,
  percent       integer not null default 0,
  finished      integer not null default 0,
  count         integer not null default 0,
  current_ref   text,
  current_title text,
  seconds       integer not null default 0,
  updated_at    timestamptz not null default now(),
  primary key (user_id, course_id)
);

-- --------------------------------------------------------------- helpers ---

create or replace function public.lantern_is_owner() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'owner')
$$;

create or replace function public.lantern_has_access(p_course text) returns boolean
language sql stable security definer set search_path = public as $$
  select public.lantern_is_owner() or exists (
    select 1 from public.courses c
    where c.id = p_course and c.status = 'published'
      and (c.visibility = 'open'
           or exists (select 1 from public.grants g where g.user_id = auth.uid() and g.course_id = c.id)))
$$;

create or replace function public.lantern_require_owner() returns void
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.lantern_is_owner() then raise exception 'Only the owner of this Lantern hub can do that.' using errcode = '42501'; end if;
end $$;

create or replace function public.lantern_require_user() returns uuid
language plpgsql stable security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'Sign in first.' using errcode = '42501'; end if;
  return auth.uid();
end $$;

-- An offer, unless the person already has the course or already has one waiting.
create or replace function public.lantern_make_offer(p_from uuid, p_to uuid, p_course text, p_message text, p_via text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if exists (select 1 from public.profiles where id = p_to and role = 'owner') then return false; end if;
  if exists (select 1 from public.grants where user_id = p_to and course_id = p_course) then return false; end if;
  if exists (select 1 from public.course_offers where to_user = p_to and course_id = p_course and status = 'pending') then return false; end if;
  insert into public.course_offers (from_user, to_user, course_id, message, via)
  values (p_from, p_to, p_course, left(coalesce(p_message, ''), 500), coalesce(p_via, 'direct'));
  return true;
end $$;

-- An offer to an email address. If an account already uses that email, the
-- offer goes to the account; otherwise it waits for them.
create or replace function public.lantern_make_email_offer(p_from uuid, p_email text, p_course text, p_message text, p_via text)
returns boolean language plpgsql security definer set search_path = public as $$
declare who uuid; e text := lower(trim(p_email));
begin
  if e !~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$' then raise exception 'That is not an email address: %', p_email; end if;
  select id into who from public.profiles where lower(email) = e limit 1;
  if who is not null then return public.lantern_make_offer(p_from, who, p_course, p_message, p_via); end if;
  if exists (select 1 from public.course_offers where to_user is null and lower(to_email) = e and course_id = p_course and status = 'pending') then return false; end if;
  insert into public.course_offers (from_user, to_email, course_id, message, via)
  values (p_from, e, p_course, left(coalesce(p_message, ''), 500), coalesce(p_via, 'direct'));
  return true;
end $$;

-- Offers waiting for this email, now that its owner has a verified account.
create or replace function public.lantern_attach_email_offers(p_user uuid) returns integer
language plpgsql security definer set search_path = public as $$
declare e text; n integer;
begin
  select lower(email) into e from auth.users where id = p_user and email_confirmed_at is not null;
  if e is null then return 0; end if;
  update public.course_offers o set to_user = p_user
  where o.to_user is null and lower(o.to_email) = e and o.status = 'pending'
    and not exists (select 1 from public.course_offers x where x.to_user = p_user and x.course_id = o.course_id and x.status = 'pending')
    and not exists (select 1 from public.grants g where g.user_id = p_user and g.course_id = o.course_id);
  get diagnostics n = row_count;
  return n;
end $$;

-- ---------------------------------------------------------- for everyone ---

create or replace function public.lantern_me() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); p public.profiles;
begin
  select * into p from public.profiles where id = u;
  if not found then
    insert into public.profiles (id, email, display_name)
      select id, email, split_part(email, '@', 1) from auth.users where id = u
      on conflict (id) do nothing;
    select * into p from public.profiles where id = u;
  end if;
  perform public.lantern_attach_email_offers(u);
  return jsonb_build_object('id', p.id, 'email', p.email, 'display_name', p.display_name, 'role', p.role,
    'owner_exists', exists (select 1 from public.profiles where role = 'owner'));
end $$;

create or replace function public.lantern_set_name(p_name text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  if length(trim(coalesce(p_name, ''))) = 0 then raise exception 'A name is needed.'; end if;
  update public.profiles set display_name = left(trim(p_name), 80) where id = u;
  return public.lantern_me();
end $$;

-- The first owner: whoever enters the claim code while there is no owner yet.
create or replace function public.lantern_claim_owner(p_code text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); want text;
begin
  if exists (select 1 from public.profiles where role = 'owner') then
    raise exception 'This hub already has an owner.';
  end if;
  select value into want from public.app_secrets where key = 'owner_claim_code';
  if want is null or p_code is distinct from want then raise exception 'That claim code is not right.'; end if;
  update public.profiles set role = 'owner' where id = u;
  return public.lantern_me();
end $$;

create or replace function public.lantern_heartbeat(p_device text, p_version text, p_course text, p_lesson text, p_status text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  insert into public.presence (user_id, device_id, last_seen, app_version, course_id, lesson_id, status)
  values (u, left(p_device, 80), now(), left(p_version, 40), p_course, p_lesson, left(p_status, 40))
  on conflict (user_id, device_id) do update set last_seen = now(), app_version = excluded.app_version,
    course_id = excluded.course_id, lesson_id = excluded.lesson_id, status = excluded.status;
  return jsonb_build_object('now', (extract(epoch from now()) * 1000)::bigint);
end $$;

-- The courses this person may open, with the newest version of each.
create or replace function public.lantern_my_courses() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); owner boolean := public.lantern_is_owner();
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', c.id, 'title', c.title, 'description', c.description, 'status', c.status,
      'visibility', c.visibility, 'listed', c.listed, 'latest_version', c.latest_version,
      'pack_path', v.pack_path, 'size', v.size, 'sha256', v.sha256, 'changelog', v.changelog,
      'access', case when owner then 'owner' when exists (select 1 from public.grants g where g.user_id = u and g.course_id = c.id) then 'granted' else 'open' end
    ) order by c.title)
    from public.courses c
    left join public.course_versions v on v.course_id = c.id and v.version = c.latest_version
    where owner or (c.status = 'published' and (c.visibility = 'open'
      or exists (select 1 from public.grants g where g.user_id = u and g.course_id = c.id)))
  ), '[]'::jsonb);
end $$;

-- Published, listed courses this person does not have yet (titles only).
create or replace function public.lantern_listed_courses() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', c.id, 'title', c.title, 'description', c.description,
      'requested', exists (select 1 from public.course_requests r where r.user_id = u and r.course_id = c.id and r.status = 'pending')) order by c.title)
    from public.courses c
    where c.status = 'published' and c.listed and not public.lantern_has_access(c.id)
  ), '[]'::jsonb);
end $$;

create or replace function public.lantern_request_course(p_course text, p_message text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  if not exists (select 1 from public.courses where id = p_course and status = 'published' and listed) then
    raise exception 'That course cannot be requested.';
  end if;
  insert into public.course_requests (user_id, course_id, message) values (u, p_course, left(coalesce(p_message, ''), 500))
  on conflict do nothing;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_my_offers() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', o.id, 'course_id', o.course_id, 'course_title', c.title,
      'course_description', c.description, 'from_name', coalesce(p.display_name, 'Someone'), 'message', o.message,
      'status', o.status, 'via', o.via, 'created_at', o.created_at) order by o.created_at desc)
    from public.course_offers o
    join public.courses c on c.id = o.course_id
    left join public.profiles p on p.id = o.from_user
    where o.to_user = u and o.status = 'pending'
  ), '[]'::jsonb);
end $$;

create or replace function public.lantern_accept_offer(p_offer uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); o public.course_offers;
begin
  select * into o from public.course_offers where id = p_offer and to_user = u for update;
  if not found then raise exception 'That offer was not found.'; end if;
  if o.status <> 'pending' then raise exception 'That offer is no longer waiting (it was %).', o.status; end if;
  insert into public.grants (user_id, course_id, granted_by, via) values (u, o.course_id, o.from_user, 'offer')
  on conflict (user_id, course_id) do nothing;
  update public.course_offers set status = 'accepted', responded_at = now() where id = p_offer;
  return jsonb_build_object('course_id', o.course_id);
end $$;

create or replace function public.lantern_decline_offer(p_offer uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  update public.course_offers set status = 'declined', responded_at = now()
  where id = p_offer and to_user = u and status = 'pending';
  if not found then raise exception 'That offer is no longer waiting.'; end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_redeem_invite(p_code text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); i public.invites; c text; n integer := 0;
begin
  select * into i from public.invites where code = upper(trim(p_code)) for update;
  if not found then raise exception 'That invite code was not found.'; end if;
  if i.expires_at is not null and i.expires_at < now() then raise exception 'That invite has expired.'; end if;
  if i.max_uses is not null and i.uses >= i.max_uses then raise exception 'That invite has been used up.'; end if;
  foreach c in array i.course_ids loop
    if public.lantern_make_offer(i.created_by, u, c, i.message, 'invite') then n := n + 1; end if;
  end loop;
  update public.invites set uses = uses + 1 where code = i.code;
  return jsonb_build_object('offers', n);
end $$;

-- ------------------------------------------------------------- progress ---

create or replace function public.lantern_pull(p_course text, p_since bigint default 0) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); snap public.progress_snapshots;
begin
  select * into snap from public.progress_snapshots where user_id = u and course_id = p_course;
  return jsonb_build_object(
    'items', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'ref', ref, 'completed', completed, 'best', best,
               'attempts', attempts, 'first_done_at', first_done_at, 'updated_at', updated_at))
               from public.progress_items where user_id = u and course_id = p_course), '[]'::jsonb),
    'seconds', coalesce((select sum(seconds) from public.progress_time where user_id = u and course_id = p_course), 0),
    'position', (select jsonb_build_object('ref', ref, 'at', at) from public.progress_position where user_id = u and course_id = p_course),
    'snapshot', case when snap.at is not null and snap.at > coalesce(p_since, 0) then jsonb_build_object('keys', snap.state, 'at', snap.at) else null end
  );
end $$;

create or replace function public.lantern_sync(p_course text, p_device text, p_items jsonb, p_time jsonb,
  p_position jsonb, p_summary jsonb, p_snapshot jsonb, p_since bigint default 0) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); it jsonb;
begin
  if not public.lantern_has_access(p_course) then raise exception 'You do not have % any more.', p_course using errcode = '42501'; end if;
  for it in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) loop
    insert into public.progress_items as pi (user_id, course_id, kind, ref, completed, best, attempts, first_done_at, updated_at)
    values (u, p_course, it->>'kind', it->>'ref', coalesce((it->>'completed')::boolean, false),
            coalesce((it->>'best')::numeric, 0), coalesce((it->>'attempts')::integer, 0),
            (it->>'first_done_at')::bigint, coalesce((it->>'updated_at')::bigint, 0))
    on conflict (user_id, course_id, kind, ref) do update set
      completed     = pi.completed or excluded.completed,
      best          = greatest(pi.best, excluded.best),
      attempts      = greatest(pi.attempts, excluded.attempts),
      first_done_at = least(pi.first_done_at, excluded.first_done_at),
      updated_at    = greatest(pi.updated_at, excluded.updated_at);
  end loop;
  for it in select * from jsonb_array_elements(coalesce(p_time, '[]'::jsonb)) loop
    insert into public.progress_time (user_id, id, course_id, seconds, at)
    values (u, it->>'id', p_course, greatest(0, coalesce((it->>'seconds')::integer, 0)), (it->>'at')::bigint)
    on conflict (user_id, id) do nothing;
  end loop;
  if p_position is not null and jsonb_typeof(p_position) = 'object' then
    insert into public.progress_position as pp (user_id, course_id, ref, at)
    values (u, p_course, p_position->>'ref', (p_position->>'at')::bigint)
    on conflict (user_id, course_id) do update set ref = excluded.ref, at = excluded.at where excluded.at > pp.at;
  end if;
  if p_snapshot is not null and jsonb_typeof(p_snapshot) = 'object' then
    insert into public.progress_snapshots as ps (user_id, course_id, state, at, device_id)
    values (u, p_course, p_snapshot->'keys', (p_snapshot->>'at')::bigint, p_device)
    on conflict (user_id, course_id) do update set state = excluded.state, at = excluded.at, device_id = excluded.device_id
      where excluded.at > ps.at;
  end if;
  if p_summary is not null and jsonb_typeof(p_summary) = 'object' then
    insert into public.progress_summary (user_id, course_id, percent, finished, count, current_ref, current_title, seconds, updated_at)
    values (u, p_course, coalesce((p_summary->>'percent')::integer, 0), coalesce((p_summary->>'finished')::integer, 0),
            coalesce((p_summary->>'count')::integer, 0), p_summary->>'current_ref', p_summary->>'current_title',
            coalesce((select sum(seconds) from public.progress_time where user_id = u and course_id = p_course), 0), now())
    on conflict (user_id, course_id) do update set percent = excluded.percent, finished = excluded.finished,
      count = excluded.count, current_ref = excluded.current_ref, current_title = excluded.current_title,
      seconds = excluded.seconds, updated_at = now();
  end if;
  return public.lantern_pull(p_course, p_since);
end $$;

-- ------------------------------------------------------------ owner only ---

create or replace function public.lantern_owner_people() returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(x order by x->>'display_name') from (
      select jsonb_build_object(
        'id', p.id, 'email', p.email, 'display_name', p.display_name, 'role', p.role, 'created_at', p.created_at,
        'last_seen', pr.last_seen, 'online', coalesce(pr.last_seen > now() - interval '2 minutes', false),
        'app_version', pr.app_version, 'current_course', pr.course_id, 'current_lesson', pr.lesson_id, 'status', pr.status,
        'groups', coalesce((select jsonb_agg(g.name) from public.group_members gm join public.groups g on g.id = gm.group_id where gm.user_id = p.id), '[]'::jsonb),
        'courses', coalesce((select jsonb_agg(jsonb_build_object('course_id', s.course_id, 'percent', s.percent, 'finished', s.finished,
            'count', s.count, 'current_ref', s.current_ref, 'current_title', s.current_title, 'seconds', s.seconds, 'updated_at', s.updated_at))
            from public.progress_summary s where s.user_id = p.id), '[]'::jsonb),
        'granted', coalesce((select jsonb_agg(g.course_id) from public.grants g where g.user_id = p.id), '[]'::jsonb)
      ) as x
      from public.profiles p
      left join lateral (select * from public.presence z where z.user_id = p.id order by z.last_seen desc limit 1) pr on true
      union all
      -- people invited by email who have no account yet
      select jsonb_build_object('id', null, 'email', lower(o.to_email), 'display_name', lower(o.to_email), 'role', 'invited',
        'pending_invite', true, 'online', false, 'courses', '[]'::jsonb, 'granted', '[]'::jsonb, 'groups', '[]'::jsonb,
        'offered', jsonb_agg(o.course_id))
      from public.course_offers o
      where o.to_user is null and o.status = 'pending'
      group by lower(o.to_email)
    ) q
  ), '[]'::jsonb);
end $$;

-- Dayspring's name for the owner's people list.
create or replace function public.lantern_people_list() returns jsonb
language sql security definer set search_path = public as $$ select public.lantern_owner_people() $$;

create or replace function public.lantern_owner_courses() returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', c.id, 'title', c.title, 'description', c.description, 'status', c.status, 'visibility', c.visibility,
      'listed', c.listed, 'latest_version', c.latest_version,
      'versions', coalesce((select jsonb_agg(jsonb_build_object('version', v.version, 'published_at', v.published_at, 'changelog', v.changelog) order by v.published_at desc)
                  from public.course_versions v where v.course_id = c.id), '[]'::jsonb),
      'holders', coalesce((select jsonb_agg(jsonb_build_object('user_id', g.user_id, 'display_name', p.display_name, 'via', g.via,
                  'percent', coalesce(s.percent, 0), 'current_title', s.current_title, 'updated_at', s.updated_at))
                  from public.grants g join public.profiles p on p.id = g.user_id
                  left join public.progress_summary s on s.user_id = g.user_id and s.course_id = g.course_id
                  where g.course_id = c.id), '[]'::jsonb),
      'pending', coalesce((select jsonb_agg(jsonb_build_object('offer_id', o.id, 'user_id', o.to_user, 'display_name', p.display_name, 'created_at', o.created_at))
                  from public.course_offers o join public.profiles p on p.id = o.to_user
                  where o.course_id = c.id and o.status = 'pending'), '[]'::jsonb)
    ) order by c.title)
    from public.courses c
  ), '[]'::jsonb);
end $$;

-- Send a course to one or many people (accounts and/or email addresses).
-- Returns how many offers were made (people who already have it are skipped).
create or replace function public.lantern_owner_send(p_users uuid[], p_course text, p_message text, p_emails text[] default '{}') returns jsonb
language plpgsql security definer set search_path = public as $$
declare x uuid; e text; n integer := 0;
begin
  perform public.lantern_require_owner();
  if not exists (select 1 from public.courses where id = p_course) then raise exception 'There is no course %.', p_course; end if;
  foreach x in array coalesce(p_users, '{}'::uuid[]) loop
    if public.lantern_make_offer(auth.uid(), x, p_course, p_message, 'direct') then n := n + 1; end if;
  end loop;
  foreach e in array coalesce(p_emails, '{}'::text[]) loop
    if public.lantern_make_email_offer(auth.uid(), e, p_course, p_message, 'direct') then n := n + 1; end if;
  end loop;
  return jsonb_build_object('offers', n);
end $$;

-- One recipient, named by account id OR email (for Dayspring: "send the
-- ColdFusion course to sam@example.com").
create or replace function public.lantern_send_offer(p_to text, p_course text, p_message text) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  if p_to ~ '^[0-9a-fA-F-]{36}$' then
    return public.lantern_owner_send(array[p_to::uuid], p_course, p_message, '{}');
  end if;
  return public.lantern_owner_send('{}', p_course, p_message, array[p_to]);
end $$;

create or replace function public.lantern_owner_offers() returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', o.id, 'to_user', o.to_user, 'to_email', o.to_email,
      'to_name', coalesce(p.display_name, o.to_email), 'course_id', o.course_id,
      'course_title', c.title, 'message', o.message, 'status', o.status, 'via', o.via, 'created_at', o.created_at,
      'responded_at', o.responded_at) order by o.created_at desc)
    from public.course_offers o left join public.profiles p on p.id = o.to_user join public.courses c on c.id = o.course_id
  ), '[]'::jsonb);
end $$;

create or replace function public.lantern_owner_withdraw(p_offer uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  update public.course_offers set status = 'withdrawn', responded_at = now() where id = p_offer and status = 'pending';
  if not found then raise exception 'That offer is no longer waiting.'; end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_owner_invite(p_courses text[], p_message text, p_days integer, p_uses integer) returns jsonb
language plpgsql security definer set search_path = public as $$
declare code text := upper(encode(gen_random_bytes(5), 'hex'));
begin
  perform public.lantern_require_owner();
  insert into public.invites (code, created_by, course_ids, message, expires_at, max_uses)
  values (code, auth.uid(), p_courses, left(coalesce(p_message, ''), 500),
          case when p_days is null then null else now() + make_interval(days => p_days) end, p_uses);
  return jsonb_build_object('code', code);
end $$;

create or replace function public.lantern_owner_grant(p_user uuid, p_course text, p_on boolean) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  if p_on then
    insert into public.grants (user_id, course_id, granted_by, via) values (p_user, p_course, auth.uid(), 'grant') on conflict do nothing;
  else
    delete from public.grants where user_id = p_user and course_id = p_course;
  end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_owner_save_course(p_id text, p_title text, p_description text,
  p_status text, p_visibility text, p_listed boolean) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  insert into public.courses (id, title, description, status, visibility, listed)
  values (p_id, p_title, coalesce(p_description, ''), coalesce(p_status, 'draft'), coalesce(p_visibility, 'private'), coalesce(p_listed, false))
  on conflict (id) do update set title = coalesce(excluded.title, courses.title),
    description = coalesce(p_description, courses.description), status = coalesce(p_status, courses.status),
    visibility = coalesce(p_visibility, courses.visibility), listed = coalesce(p_listed, courses.listed), updated_at = now();
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_owner_publish(p_course text, p_version text, p_pack_path text, p_size bigint,
  p_sha256 text, p_changelog text, p_manifest jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  insert into public.course_versions (course_id, version, pack_path, size, sha256, changelog, manifest)
  values (p_course, p_version, p_pack_path, p_size, p_sha256, coalesce(p_changelog, ''), p_manifest)
  on conflict (course_id, version) do update set pack_path = excluded.pack_path, size = excluded.size,
    sha256 = excluded.sha256, changelog = excluded.changelog, manifest = excluded.manifest, published_at = now();
  update public.courses set latest_version = p_version, updated_at = now() where id = p_course;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_owner_groups() returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', g.id, 'name', g.name,
      'members', coalesce((select jsonb_agg(jsonb_build_object('user_id', m.user_id, 'display_name', p.display_name))
                 from public.group_members m join public.profiles p on p.id = m.user_id where m.group_id = g.id), '[]'::jsonb),
      'courses', coalesce((select jsonb_agg(gc.course_id) from public.group_courses gc where gc.group_id = g.id), '[]'::jsonb)
    ) order by g.name)
    from public.groups g
  ), '[]'::jsonb);
end $$;

create or replace function public.lantern_owner_group_save(p_id uuid, p_name text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare gid uuid;
begin
  perform public.lantern_require_owner();
  if p_id is null then
    insert into public.groups (name) values (left(trim(p_name), 80)) returning id into gid;
  else
    update public.groups set name = left(trim(p_name), 80) where id = p_id returning id into gid;
  end if;
  return jsonb_build_object('id', gid);
end $$;

-- Add or remove people. Somebody added is offered every course the group has.
create or replace function public.lantern_owner_group_members(p_group uuid, p_add uuid[], p_remove uuid[]) returns jsonb
language plpgsql security definer set search_path = public as $$
declare x uuid; gc record; n integer := 0;
begin
  perform public.lantern_require_owner();
  foreach x in array coalesce(p_add, '{}'::uuid[]) loop
    insert into public.group_members (group_id, user_id) values (p_group, x) on conflict do nothing;
    for gc in select * from public.group_courses where group_id = p_group loop
      if public.lantern_make_offer(auth.uid(), x, gc.course_id, gc.message, 'group') then n := n + 1; end if;
    end loop;
  end loop;
  delete from public.group_members where group_id = p_group and user_id = any (coalesce(p_remove, '{}'::uuid[]));
  return jsonb_build_object('offers', n);
end $$;

-- Add or remove courses. A course added is offered to everyone in the group.
create or replace function public.lantern_owner_group_courses(p_group uuid, p_add text[], p_remove text[], p_message text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare c text; m record; n integer := 0;
begin
  perform public.lantern_require_owner();
  foreach c in array coalesce(p_add, '{}'::text[]) loop
    insert into public.group_courses (group_id, course_id, message) values (p_group, c, left(coalesce(p_message, ''), 500))
    on conflict (group_id, course_id) do update set message = excluded.message;
    for m in select * from public.group_members where group_id = p_group loop
      if public.lantern_make_offer(auth.uid(), m.user_id, c, p_message, 'group') then n := n + 1; end if;
    end loop;
  end loop;
  delete from public.group_courses where group_id = p_group and course_id = any (coalesce(p_remove, '{}'::text[]));
  return jsonb_build_object('offers', n);
end $$;

create or replace function public.lantern_owner_requests() returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', r.id, 'user_id', r.user_id, 'display_name', p.display_name, 'course_id', r.course_id,
      'course_title', c.title, 'message', r.message, 'status', r.status, 'created_at', r.created_at) order by r.created_at desc)
    from public.course_requests r join public.profiles p on p.id = r.user_id join public.courses c on c.id = r.course_id
  ), '[]'::jsonb);
end $$;

create or replace function public.lantern_owner_answer_request(p_request uuid, p_approve boolean) returns jsonb
language plpgsql security definer set search_path = public as $$
declare r public.course_requests;
begin
  perform public.lantern_require_owner();
  select * into r from public.course_requests where id = p_request and status = 'pending' for update;
  if not found then raise exception 'That request is no longer waiting.'; end if;
  if p_approve then
    insert into public.grants (user_id, course_id, granted_by, via) values (r.user_id, r.course_id, auth.uid(), 'request') on conflict do nothing;
  end if;
  update public.course_requests set status = case when p_approve then 'approved' else 'declined' end, answered_at = now() where id = p_request;
  return jsonb_build_object('ok', true);
end $$;

-- ------------------------------------------------------ row level security ---
-- Reads only; writes go through the functions above.

do $$
declare t text;
begin
  foreach t in array array['profiles','app_secrets','courses','course_versions','grants','course_offers','invites',
    'groups','group_members','group_courses','course_requests','presence','progress_items','progress_time',
    'progress_position','progress_snapshots','progress_summary'] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

drop policy if exists lantern_profiles_read on public.profiles;
create policy lantern_profiles_read on public.profiles for select to authenticated
  using (id = auth.uid() or public.lantern_is_owner());

drop policy if exists lantern_courses_read on public.courses;
create policy lantern_courses_read on public.courses for select to authenticated
  using (public.lantern_has_access(id));

drop policy if exists lantern_versions_read on public.course_versions;
create policy lantern_versions_read on public.course_versions for select to authenticated
  using (public.lantern_has_access(course_id));

drop policy if exists lantern_grants_read on public.grants;
create policy lantern_grants_read on public.grants for select to authenticated
  using (user_id = auth.uid() or public.lantern_is_owner());

drop policy if exists lantern_offers_read on public.course_offers;
create policy lantern_offers_read on public.course_offers for select to authenticated
  using (to_user = auth.uid() or public.lantern_is_owner());

drop policy if exists lantern_requests_read on public.course_requests;
create policy lantern_requests_read on public.course_requests for select to authenticated
  using (user_id = auth.uid() or public.lantern_is_owner());

do $$
declare t text;
begin
  foreach t in array array['presence','progress_items','progress_time','progress_position','progress_snapshots','progress_summary'] loop
    execute format('drop policy if exists lantern_own_read on public.%I', t);
    execute format('create policy lantern_own_read on public.%I for select to authenticated using (user_id = auth.uid() or public.lantern_is_owner())', t);
  end loop;
  foreach t in array array['invites','groups','group_members','group_courses'] loop
    execute format('drop policy if exists lantern_owner_read on public.%I', t);
    execute format('create policy lantern_owner_read on public.%I for select to authenticated using (public.lantern_is_owner())', t);
  end loop;
end $$;

-- Functions are for signed-in people only.
do $$
declare f record;
begin
  for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname like 'lantern\_%'
             -- internal helpers (they trust the ids they are given) stay locked; see 0003
             and p.proname not in ('lantern_make_offer', 'lantern_make_email_offer', 'lantern_attach_email_offers', 'lantern_attach_friend_requests', 'lantern_befriend', 'lantern_are_friends', 'lantern_blocked_either', 'lantern_relation', 'lantern_resolve_person', 'lantern_new_friend_code', 'lantern_new_user', 'lantern_profile_code', 'lantern_require_user', 'lantern_require_owner') loop
    execute format('revoke all on function %s from public, anon', f.sig);
    execute format('grant execute on function %s to authenticated', f.sig);
  end loop;
end $$;

-- ---------------------------------------------------------------- storage ---

insert into storage.buckets (id, name, public) values ('course-packs', 'course-packs', false)
on conflict (id) do nothing;

drop policy if exists lantern_packs_read on storage.objects;
create policy lantern_packs_read on storage.objects for select to authenticated
  using (bucket_id = 'course-packs' and public.lantern_has_access(split_part(name, '/', 1)));

drop policy if exists lantern_packs_insert on storage.objects;
create policy lantern_packs_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'course-packs' and public.lantern_is_owner());

drop policy if exists lantern_packs_update on storage.objects;
create policy lantern_packs_update on storage.objects for update to authenticated
  using (bucket_id = 'course-packs' and public.lantern_is_owner());

drop policy if exists lantern_packs_delete on storage.objects;
create policy lantern_packs_delete on storage.objects for delete to authenticated
  using (bucket_id = 'course-packs' and public.lantern_is_owner());


-- ------------------------------------------------------------ preferences ---
-- A person's settings that follow them between computers (the code editor,
-- appearance). Newest wins.
create table if not exists public.preferences (
  user_id    uuid primary key references public.profiles(id) on delete cascade,
  prefs      jsonb not null default '{}'::jsonb,
  updated_at bigint not null default 0
);
alter table public.preferences enable row level security;
drop policy if exists lantern_own_read on public.preferences;
create policy lantern_own_read on public.preferences for select to authenticated using (user_id = auth.uid());

create or replace function public.lantern_prefs_get() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); p public.preferences;
begin
  select * into p from public.preferences where user_id = u;
  return jsonb_build_object('prefs', coalesce(p.prefs, '{}'::jsonb), 'updated_at', coalesce(p.updated_at, 0));
end $$;

create or replace function public.lantern_prefs_set(p_prefs jsonb, p_updated_at bigint) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  if pg_column_size(p_prefs) > 64000 then raise exception 'Those settings are too large.'; end if;
  insert into public.preferences as x (user_id, prefs, updated_at) values (u, coalesce(p_prefs, '{}'::jsonb), p_updated_at)
  on conflict (user_id) do update set prefs = excluded.prefs, updated_at = excluded.updated_at where excluded.updated_at > x.updated_at;
  return public.lantern_prefs_get();
end $$;

revoke all on function public.lantern_prefs_get() from public, anon;
revoke all on function public.lantern_prefs_set(jsonb, bigint) from public, anon;
grant execute on function public.lantern_prefs_get() to authenticated;
grant execute on function public.lantern_prefs_set(jsonb, bigint) to authenticated;

-- --------------------------------------------------------------- the end ---
-- Your one-time owner claim code. Copy it; you enter it in Lantern
-- (Settings → Account & hub → "I set up this hub") after you sign up in the app.
-- (the owner claim code is shown at the end of this file)

-- ##########################################################################
-- 0002_friends.sql
-- ##########################################################################

-- ===========================================================================
-- supabase/migrations/0002_friends.sql — friends on the Lantern hub.
-- ---------------------------------------------------------------------------
-- Run after 0001 (SQL Editor → New query → paste → Run). Safe to run again.
-- A new hub can paste supabase/lantern_hub_all.sql instead, which is 0001 and
-- this file together.
--
-- What it adds:
--   * every person gets a short FRIEND CODE (like LNT-7K3Q) they can share
--   * who can find you: by your exact email or friend code (always), and by
--     your name only if you turn that on. The owner can see everyone anyway.
--   * FRIEND REQUESTS: pending → accepted / declined / ignored / cancelled.
--     "Ignored" stays waiting for the person who got it (they can still
--     accept later); the sender just sees "waiting".
--     A request can go to an email address that has no account yet; it
--     attaches when that person signs up (in Lantern, or in Dayspring's
--     "Connect to Lantern").
--   * FRIENDSHIPS (both ways) and BLOCKS (a blocked person cannot send you
--     requests and does not see you in search).
--   * at most 20 requests a day per person; after a "no", the same person
--     can be asked again after 7 days.
--
-- Courses still go out only from the owner (lantern_owner_send). The app's
-- normal path is friends first; the owner may still send to anyone.
-- ===========================================================================

-- ---------------------------------------------------------------- people ---

alter table public.profiles add column if not exists friend_code text;
alter table public.profiles add column if not exists findable_by_name boolean not null default false;
create unique index if not exists profiles_friend_code_key on public.profiles (friend_code);

-- LNT- and four characters without look-alikes (no 0/O, 1/I/L).
create or replace function public.lantern_new_friend_code() returns text
language plpgsql volatile security definer set search_path = public as $$
declare alphabet text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; c text; i int;
begin
  loop
    c := 'LNT-';
    for i in 1..4 loop c := c || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1); end loop;
    exit when not exists (select 1 from public.profiles where friend_code = c);
  end loop;
  return c;
end $$;

create or replace function public.lantern_profile_code() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.friend_code is null then new.friend_code := public.lantern_new_friend_code(); end if;
  return new;
end $$;

drop trigger if exists lantern_profile_code on public.profiles;
create trigger lantern_profile_code before insert on public.profiles
  for each row execute function public.lantern_profile_code();

-- people who were here before this file get a code too
do $$
declare r record;
begin
  for r in select id from public.profiles where friend_code is null loop
    update public.profiles set friend_code = public.lantern_new_friend_code() where id = r.id;
  end loop;
end $$;

-- --------------------------------------------------------------- friends ---

create table if not exists public.friend_requests (
  id           uuid primary key default gen_random_uuid(),
  from_user    uuid not null references public.profiles(id) on delete cascade,
  to_user      uuid references public.profiles(id) on delete cascade,
  to_email     text,
  message      text not null default '',
  status       text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'ignored', 'cancelled')),
  created_at   timestamptz not null default now(),
  responded_at timestamptz,
  check (to_user is not null or to_email is not null)
);
create index if not exists friend_requests_to on public.friend_requests (to_user, status);
create index if not exists friend_requests_from on public.friend_requests (from_user, created_at);
-- one open request per pair (pending or ignored count as open)
create unique index if not exists friend_requests_open_pair on public.friend_requests (from_user, to_user)
  where status in ('pending', 'ignored') and to_user is not null;
create unique index if not exists friend_requests_open_email on public.friend_requests (from_user, lower(to_email))
  where status in ('pending', 'ignored') and to_user is null;

create table if not exists public.friendships (
  user_a     uuid not null references public.profiles(id) on delete cascade,
  user_b     uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_a, user_b),
  check (user_a < user_b)
);

create table if not exists public.blocks (
  blocker    uuid not null references public.profiles(id) on delete cascade,
  blocked    uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker, blocked)
);

-- --------------------------------------------------------------- helpers ---

create or replace function public.lantern_are_friends(p_a uuid, p_b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.friendships where user_a = least(p_a, p_b) and user_b = greatest(p_a, p_b))
$$;

create or replace function public.lantern_blocked_either(p_a uuid, p_b uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.blocks where (blocker = p_a and blocked = p_b) or (blocker = p_b and blocked = p_a))
$$;

create or replace function public.lantern_befriend(p_a uuid, p_b uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.friendships (user_a, user_b) values (least(p_a, p_b), greatest(p_a, p_b)) on conflict do nothing;
end $$;

-- Requests waiting for this email, now that its owner has a verified account.
create or replace function public.lantern_attach_friend_requests(p_user uuid) returns integer
language plpgsql security definer set search_path = public as $$
declare e text; n integer;
begin
  select lower(email) into e from auth.users where id = p_user and email_confirmed_at is not null;
  if e is null then return 0; end if;
  -- a second request from the same person to the same email is dropped
  update public.friend_requests r set status = 'cancelled', responded_at = now()
  where r.to_user is null and lower(r.to_email) = e and r.status in ('pending', 'ignored')
    and (r.from_user = p_user
         or exists (select 1 from public.friend_requests x where x.from_user = r.from_user and x.to_user = p_user and x.status in ('pending', 'ignored'))
         or public.lantern_are_friends(r.from_user, p_user));
  update public.friend_requests r set to_user = p_user
  where r.to_user is null and lower(r.to_email) = e and r.status in ('pending', 'ignored');
  get diagnostics n = row_count;
  return n;
end $$;

-- Who a query names: an account id, a friend code, or an exact email.
create or replace function public.lantern_resolve_person(p_to text) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare t text := trim(coalesce(p_to, '')); who uuid;
begin
  if t ~ '^[0-9a-fA-F-]{36}$' then select id into who from public.profiles where id = t::uuid;
  elsif upper(t) ~ '^(LNT-)?[A-Z0-9]{4}$' then
    select id into who from public.profiles where friend_code = case when upper(t) like 'LNT-%' then upper(t) else 'LNT-' || upper(t) end;
  elsif t like '%@%' then select id into who from public.profiles where lower(email) = lower(t) limit 1;
  end if;
  return who;
end $$;

-- ---------------------------------------------------------- for everyone ---

-- lantern_me also hands back your friend code and attaches waiting requests.
create or replace function public.lantern_me() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); p public.profiles;
begin
  select * into p from public.profiles where id = u;
  if not found then
    insert into public.profiles (id, email, display_name)
      select id, email, split_part(email, '@', 1) from auth.users where id = u
      on conflict (id) do nothing;
    select * into p from public.profiles where id = u;
  end if;
  if p.friend_code is null then
    update public.profiles set friend_code = public.lantern_new_friend_code() where id = u returning * into p;
  end if;
  perform public.lantern_attach_email_offers(u);
  perform public.lantern_attach_friend_requests(u);
  return jsonb_build_object('id', p.id, 'email', p.email, 'display_name', p.display_name, 'role', p.role,
    'friend_code', p.friend_code, 'findable_by_name', p.findable_by_name,
    'owner_exists', exists (select 1 from public.profiles where role = 'owner'));
end $$;

create or replace function public.lantern_set_findable(p_by_name boolean) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  update public.profiles set findable_by_name = coalesce(p_by_name, false) where id = u;
  return public.lantern_me();
end $$;

-- How the asker stands with someone: you, friend, sent, received, blocked, none.
create or replace function public.lantern_relation(p_me uuid, p_other uuid) returns text
language sql stable security definer set search_path = public as $$
  select case
    when p_me = p_other then 'you'
    when exists (select 1 from public.blocks where blocker = p_me and blocked = p_other) then 'blocked'
    when public.lantern_are_friends(p_me, p_other) then 'friend'
    when exists (select 1 from public.friend_requests where from_user = p_me and to_user = p_other and status in ('pending', 'ignored')) then 'sent'
    when exists (select 1 from public.friend_requests where from_user = p_other and to_user = p_me and status in ('pending', 'ignored')) then 'received'
    else 'none' end
$$;

-- Find people. Everyone: exact email or friend code, or a name among people
-- who allow name search. The owner: anyone, by any part of name or email.
create or replace function public.lantern_find_people(p_query text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); q text := trim(coalesce(p_query, '')); owner boolean := public.lantern_is_owner(); code text;
begin
  if length(q) < 2 then return '[]'::jsonb; end if;
  code := case when upper(q) like 'LNT-%' then upper(q) else 'LNT-' || upper(q) end;
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', p.id, 'display_name', p.display_name, 'friend_code', p.friend_code,
      'email', case when owner then p.email else null end,
      'relation', public.lantern_relation(u, p.id)) order by p.display_name)
    from (
      select * from public.profiles p
      where p.id <> u
        and not exists (select 1 from public.blocks b where b.blocker = p.id and b.blocked = u)
        and (p.friend_code = code
             or lower(p.email) = lower(q)
             or (p.findable_by_name and length(q) >= 3 and p.display_name ilike '%' || q || '%')
             or (owner and (p.display_name ilike '%' || q || '%' or p.email ilike '%' || q || '%')))
      limit 20
    ) p
  ), '[]'::jsonb);
end $$;

-- Ask someone to be friends: an account id, a friend code, or an email (an
-- email with no account yet waits for them). If they already asked you, this
-- accepts theirs instead.
create or replace function public.lantern_send_friend_request(p_to text, p_message text default '') returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); who uuid; e text; r public.friend_requests; recent integer;
begin
  who := public.lantern_resolve_person(p_to);
  if who is null and trim(coalesce(p_to, '')) like '%@%' then
    e := lower(trim(p_to));
    if e !~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$' then raise exception 'That is not an email address: %', p_to; end if;
  elsif who is null then
    raise exception 'Nobody was found with that friend code or email.';
  end if;
  if who = u then raise exception 'That is you.'; end if;
  select count(*) into recent from public.friend_requests where from_user = u and created_at > now() - interval '1 day';
  if recent >= 20 then raise exception 'That is a lot of friend requests for one day. Try again tomorrow.'; end if;

  if who is null then
    if exists (select 1 from public.friend_requests where from_user = u and to_user is null and lower(to_email) = e and status in ('pending', 'ignored')) then
      return jsonb_build_object('status', 'sent', 'waiting_for_signup', true);
    end if;
    insert into public.friend_requests (from_user, to_email, message) values (u, e, left(coalesce(p_message, ''), 300));
    return jsonb_build_object('status', 'sent', 'waiting_for_signup', true);
  end if;

  if public.lantern_blocked_either(u, who) then raise exception 'You cannot send a friend request to this person.'; end if;
  if public.lantern_are_friends(u, who) then return jsonb_build_object('status', 'friend'); end if;
  -- they asked first: that is a yes
  select * into r from public.friend_requests where from_user = who and to_user = u and status in ('pending', 'ignored') limit 1;
  if found then
    update public.friend_requests set status = 'accepted', responded_at = now() where id = r.id;
    perform public.lantern_befriend(u, who);
    return jsonb_build_object('status', 'friend', 'accepted_theirs', true);
  end if;
  if exists (select 1 from public.friend_requests where from_user = u and to_user = who and status in ('pending', 'ignored')) then
    return jsonb_build_object('status', 'sent');
  end if;
  if exists (select 1 from public.friend_requests where from_user = u and to_user = who and status = 'declined' and responded_at > now() - interval '7 days') then
    raise exception 'They said no to a request recently. You can ask again after a week.';
  end if;
  insert into public.friend_requests (from_user, to_user, message) values (u, who, left(coalesce(p_message, ''), 300));
  return jsonb_build_object('status', 'sent');
end $$;

-- accept | decline | ignore (ignore keeps it waiting, just out of the way)
create or replace function public.lantern_respond_friend_request(p_request uuid, p_action text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user(); r public.friend_requests;
begin
  select * into r from public.friend_requests where id = p_request and to_user = u;
  if not found then raise exception 'That friend request was not found.'; end if;
  if r.status not in ('pending', 'ignored') then raise exception 'That friend request is no longer waiting (it was %).', r.status; end if;
  if p_action = 'accept' then
    update public.friend_requests set status = 'accepted', responded_at = now() where id = r.id;
    perform public.lantern_befriend(u, r.from_user);
    return jsonb_build_object('status', 'friend', 'friend', r.from_user);
  elsif p_action = 'decline' then
    update public.friend_requests set status = 'declined', responded_at = now() where id = r.id;
    return jsonb_build_object('status', 'declined');
  elsif p_action = 'ignore' then
    update public.friend_requests set status = 'ignored', responded_at = now() where id = r.id;
    return jsonb_build_object('status', 'ignored');
  end if;
  raise exception 'Say accept, decline or ignore.';
end $$;

create or replace function public.lantern_cancel_friend_request(p_request uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  update public.friend_requests set status = 'cancelled', responded_at = now()
  where id = p_request and from_user = u and status in ('pending', 'ignored');
  if not found then raise exception 'That friend request is no longer waiting.'; end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_remove_friend(p_user uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  delete from public.friendships where user_a = least(u, p_user) and user_b = greatest(u, p_user);
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_block_user(p_user uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  if p_user = u then raise exception 'That is you.'; end if;
  insert into public.blocks (blocker, blocked) values (u, p_user) on conflict do nothing;
  delete from public.friendships where user_a = least(u, p_user) and user_b = greatest(u, p_user);
  update public.friend_requests set status = 'cancelled', responded_at = now()
  where status in ('pending', 'ignored') and ((from_user = u and to_user = p_user) or (from_user = p_user and to_user = u));
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.lantern_unblock_user(p_user uuid) returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  delete from public.blocks where blocker = u and blocked = p_user;
  return jsonb_build_object('ok', true);
end $$;

-- Your friends: name, code, online, and what they are studying now.
create or replace function public.lantern_my_friends() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  return coalesce((
    select jsonb_agg(jsonb_build_object('id', p.id, 'display_name', p.display_name, 'friend_code', p.friend_code, 'role', p.role,
      'since', f.created_at, 'last_seen', pr.last_seen, 'online', coalesce(pr.last_seen > now() - interval '2 minutes', false),
      'current_course', pr.course_id,
      'current_course_title', (select c.title from public.courses c where c.id = pr.course_id))
      order by p.display_name)
    from public.friendships f
    join public.profiles p on p.id = case when f.user_a = u then f.user_b else f.user_a end
    left join lateral (select * from public.presence z where z.user_id = p.id order by z.last_seen desc limit 1) pr on true
    where f.user_a = u or f.user_b = u
  ), '[]'::jsonb);
end $$;

-- Requests you got (pending and ignored) and sent (an ignored one shows as
-- "pending" to its sender), plus the people you blocked.
create or replace function public.lantern_my_friend_requests() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := public.lantern_require_user();
begin
  perform public.lantern_attach_friend_requests(u);
  return jsonb_build_object(
    'received', coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'from', r.from_user, 'from_name', p.display_name,
        'from_code', p.friend_code, 'from_role', p.role, 'message', r.message, 'status', r.status, 'created_at', r.created_at) order by r.created_at desc)
      from public.friend_requests r join public.profiles p on p.id = r.from_user
      where r.to_user = u and r.status in ('pending', 'ignored')), '[]'::jsonb),
    'sent', coalesce((select jsonb_agg(jsonb_build_object('id', r.id, 'to', r.to_user, 'to_name', coalesce(p.display_name, r.to_email),
        'to_email', case when r.to_user is null then r.to_email else null end,
        'status', case when r.status = 'ignored' then 'pending' else r.status end, 'created_at', r.created_at, 'responded_at',
        case when r.status = 'ignored' then null else r.responded_at end) order by r.created_at desc)
      from public.friend_requests r left join public.profiles p on p.id = r.to_user
      where r.from_user = u and (r.status in ('pending', 'ignored') or (r.status in ('accepted', 'declined') and r.responded_at > now() - interval '7 days'))), '[]'::jsonb),
    'blocked', coalesce((select jsonb_agg(jsonb_build_object('id', b.blocked, 'display_name', p.display_name))
      from public.blocks b join public.profiles p on p.id = b.blocked where b.blocker = u), '[]'::jsonb));
end $$;

-- The owner's People list also says who is already a friend.
create or replace function public.lantern_owner_people() returns jsonb
language plpgsql security definer set search_path = public as $$
declare u uuid := auth.uid();
begin
  perform public.lantern_require_owner();
  return coalesce((
    select jsonb_agg(x order by x->>'display_name') from (
      select jsonb_build_object(
        'id', p.id, 'email', p.email, 'display_name', p.display_name, 'role', p.role, 'created_at', p.created_at,
        'friend_code', p.friend_code, 'relation', public.lantern_relation(u, p.id),
        'last_seen', pr.last_seen, 'online', coalesce(pr.last_seen > now() - interval '2 minutes', false),
        'app_version', pr.app_version, 'current_course', pr.course_id, 'current_lesson', pr.lesson_id, 'status', pr.status,
        'groups', coalesce((select jsonb_agg(g.name) from public.group_members gm join public.groups g on g.id = gm.group_id where gm.user_id = p.id), '[]'::jsonb),
        'courses', coalesce((select jsonb_agg(jsonb_build_object('course_id', s.course_id, 'percent', s.percent, 'finished', s.finished,
            'count', s.count, 'current_ref', s.current_ref, 'current_title', s.current_title, 'seconds', s.seconds, 'updated_at', s.updated_at))
            from public.progress_summary s where s.user_id = p.id), '[]'::jsonb),
        'granted', coalesce((select jsonb_agg(g.course_id) from public.grants g where g.user_id = p.id), '[]'::jsonb)
      ) as x
      from public.profiles p
      left join lateral (select * from public.presence z where z.user_id = p.id order by z.last_seen desc limit 1) pr on true
      union all
      select jsonb_build_object('id', null, 'email', lower(o.to_email), 'display_name', lower(o.to_email), 'role', 'invited',
        'pending_invite', true, 'online', false, 'courses', '[]'::jsonb, 'granted', '[]'::jsonb, 'groups', '[]'::jsonb,
        'offered', jsonb_agg(o.course_id))
      from public.course_offers o
      where o.to_user is null and o.status = 'pending'
      group by lower(o.to_email)
    ) q
  ), '[]'::jsonb);
end $$;

-- ------------------------------------------------------ row level security ---

alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.blocks enable row level security;

drop policy if exists lantern_friend_requests_read on public.friend_requests;
create policy lantern_friend_requests_read on public.friend_requests for select to authenticated
  using (from_user = auth.uid() or to_user = auth.uid() or public.lantern_is_owner());

drop policy if exists lantern_friendships_read on public.friendships;
create policy lantern_friendships_read on public.friendships for select to authenticated
  using (user_a = auth.uid() or user_b = auth.uid() or public.lantern_is_owner());

drop policy if exists lantern_blocks_read on public.blocks;
create policy lantern_blocks_read on public.blocks for select to authenticated
  using (blocker = auth.uid());

-- Functions are for signed-in people only (the same rule as 0001, again for
-- the new ones).
do $$
declare f record;
begin
  for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname like 'lantern\_%'
             -- internal helpers (they trust the ids they are given) stay locked; see 0003
             and p.proname not in ('lantern_make_offer', 'lantern_make_email_offer', 'lantern_attach_email_offers', 'lantern_attach_friend_requests', 'lantern_befriend', 'lantern_are_friends', 'lantern_blocked_either', 'lantern_relation', 'lantern_resolve_person', 'lantern_new_friend_code', 'lantern_new_user', 'lantern_profile_code', 'lantern_require_user', 'lantern_require_owner') loop
    execute format('revoke all on function %s from public, anon', f.sig);
    execute format('grant execute on function %s to authenticated', f.sig);
  end loop;
end $$;

-- ##########################################################################
-- 0003_lock_helpers.sql
-- ##########################################################################

-- ===========================================================================
-- 0003_lock_helpers.sql — the hub's internal helpers are not for callers.
-- ---------------------------------------------------------------------------
-- 0001 and 0002 let every signed-in person run every lantern_* function. Most
-- of those are the hub's API and check who is asking. A few are INTERNAL
-- helpers that take user ids as arguments and trust them: called directly,
-- lantern_make_offer could make an "offer from the owner" to yourself (and so
-- give yourself any course), lantern_befriend could make any two people
-- friends, lantern_resolve_person could look up anyone by email.
--
-- This takes the right to call them away from everyone but the database's
-- own functions. Nothing in Lantern or Dayspring calls them directly: they
-- only run inside the lantern_* API functions (which run as the database
-- owner) and in triggers. lantern_is_owner and lantern_has_access stay
-- callable, because the row level security rules use them (and they only
-- answer about the person asking).
--
-- Safe to run again, and safe to run after 0001/0002 are run again.
-- ===========================================================================

do $$
declare f record;
begin
  for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
           where n.nspname = 'public' and p.proname in (
             'lantern_make_offer', 'lantern_make_email_offer',
             'lantern_attach_email_offers', 'lantern_attach_friend_requests',
             'lantern_befriend', 'lantern_are_friends', 'lantern_blocked_either', 'lantern_relation',
             'lantern_resolve_person', 'lantern_new_friend_code',
             'lantern_new_user', 'lantern_profile_code',
             'lantern_require_user', 'lantern_require_owner') loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
  end loop;
end $$;

-- --------------------------------------------------------------- the end ---
-- Your one-time owner claim code. Copy it; you enter it in Lantern
-- (Settings → Account & hub → "I set up this hub") after you sign up in the app.
select value as owner_claim_code from public.app_secrets where key = 'owner_claim_code';
