#!/usr/bin/env node
/* ===========================================================================
   scripts/build-hub-sql.mjs — one file for setting up a new hub.
   ---------------------------------------------------------------------------
       node scripts/build-hub-sql.mjs          write supabase/lantern_hub_all.sql
       node scripts/build-hub-sql.mjs --check  fail if it is out of date

   Joins supabase/migrations/*.sql in order into supabase/lantern_hub_all.sql,
   so a new hub pastes a single file. The owner claim code line (the last
   statement of 0001) is moved to the very end, so it is the result the SQL
   Editor shows. A hub that already ran 0001 pastes only the newer files.
   =========================================================================== */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'supabase', 'migrations');
const OUT = join(ROOT, 'supabase', 'lantern_hub_all.sql');
const CLAIM = /^select value as owner_claim_code from public\.app_secrets where key = 'owner_claim_code';\s*$/m;

export function buildHubSql() {
  const files = readdirSync(DIR).filter((f) => /^\d{4}_.*\.sql$/.test(f)).sort();
  let claim = '';
  const parts = files.map((f) => {
    let s = readFileSync(join(DIR, f), 'utf8').replace(/\r\n/g, '\n');
    const m = CLAIM.exec(s);
    if (m) { claim = m[0].trim(); s = s.replace(CLAIM, () => '-- (the owner claim code is shown at the end of this file)'); }
    return '-- ##########################################################################\n-- ' + f + '\n-- ##########################################################################\n\n' + s.trimEnd() + '\n';
  });
  const head = '-- ===========================================================================\n' +
    '-- supabase/lantern_hub_all.sql — everything a NEW Lantern hub needs, in one paste.\n' +
    '-- Generated by scripts/build-hub-sql.mjs from supabase/migrations (' + files.join(', ') + ').\n' +
    '-- Do not edit this file; edit the migrations and run the script again.\n' +
    '-- Safe to run again. The last result is your one-time owner claim code.\n' +
    '-- ===========================================================================\n\n';
  const tail = claim ? '\n-- --------------------------------------------------------------- the end ---\n-- Your one-time owner claim code. Copy it; you enter it in Lantern\n-- (Settings → Account & hub → "I set up this hub") after you sign up in the app.\n' + claim + '\n' : '';
  return head + parts.join('\n') + tail;
}

if (process.argv[1] && process.argv[1].replace(/\\/g, '/').endsWith('build-hub-sql.mjs')) {
  const sql = buildHubSql();
  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
    if (cur !== sql) { console.error('supabase/lantern_hub_all.sql is out of date: run node scripts/build-hub-sql.mjs'); process.exit(1); }
    console.log('supabase/lantern_hub_all.sql is up to date.');
  } else {
    writeFileSync(OUT, sql);
    console.log('Wrote supabase/lantern_hub_all.sql (' + sql.length + ' bytes).');
  }
}
